[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
streamdeck = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
tokio = { version = "1.19.2", features = ["full"] } 

tokio-tungstenite = "0.17.1"
