[target.arm-unknown-linux-gnueabihf]
dockerfile = "./Dockerfile.build"


###################################################################################################
###################################################################################################
# set to invalid since it doesn't work for client and not needed for server
###################################################################################################
###################################################################################################
[invalid.target.x86_64-unknown-linux-musl.dockerfile]
file = "./build/Dockerfile.build"
context = "build"

[invalid.target.x86_64-unknown-linux-musl.dockerfile.build-args]
TARGET = "amd64-unknown-linux-musl"
PKG_CONFIG_PATH="/usr/lib/amd64-linux-musl/pkgconfig"
DEB_ARCH = "amd64"

[invalid.target.aarch64-unknown-linux-musl.dockerfile]
file = "./build/Dockerfile.build"
context = "build"

[invalid.target.aarch64-unknown-linux-musl.dockerfile.build-args]
TARGET = "aarch64-unknown-linux-musl"
PKG_CONFIG_PATH="/usr/lib/aarch64-linux-musl/pkgconfig"
DEB_ARCH = "arm64"