[target.arm-unknown-linux-gnueabihf]
dockerfile = "./Dockerfile.build"

[target.x86_64-unknown-linux-musl.dockerfile]
file = "./build/Dockerfile.build"
context = "build"

[target.x86_64-unknown-linux-musl.dockerfile.build-args]
TARGET = "amd64-unknown-linux-gnu"
PKG_CONFIG_PATH="/usr/lib/amd64-linux-gnu/pkgconfig"
DEB_ARCH = "amd64"


[target.aarch64-unknown-linux-musl.dockerfile]
file = "./build/Dockerfile.build"
context = "build"

[target.aarch64-unknown-linux-musl.dockerfile.build-args]
TARGET = "aarch64-unknown-linux-gnu"
PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig"
DEB_ARCH = "aarch64"