# FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main
# RUN apt-get update
# RUN dpkg --add-architecture armhf && \
#     apt-get update && \
#     apt-get install --assume-yes libssl-dev:armhf libusb-1.0-0-dev:armhf libhidapi-dev:armhf libudev-dev:armhf
# # RUN ln -s /usr/include/arm-linux-gnueabihf/openssl/opensslconf.h \
# #           /usr/include/openssl/
# ENV PKG_CONFIG_LIBDIR_arm_unknown_linux_gnueabihf=/usr/lib/arm-linux-gnueabihf/pkgconfig
# # ENV CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS="-L /usr/lib/arm-linux-gnueabihf -C link-args=-Wl,-rpath-link,/usr/lib/arm-linux-gnueabihf $CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_RUSTFLAGS"

FROM ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main

RUN apt-get update
RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev libusb-1.0-0-dev libhidapi-dev libudev-dev libssl-dev:armhf libusb-1.0-0-dev:armhf libhidapi-dev:armhf libudev-dev:armhf

RUN ln -s /usr/include/arm-linux-gnueabihf/openssl/opensslconf.h \
           /usr/include/openssl/

ENV PKG_CONFIG_LIBDIR_arm_unknown_linux_gnueabihf=/usr/lib/arm-linux-gnueabihf/pkgconfig
