version: '3'

tasks:
  default:
    cmds:
      - task: build

  run-server:
    cmds:
      - cargo run --bin server
    silent: true
  build-server:
    cmds:
      - cargo build --bin server
    silent: true
  
  run-client:
    cmds:
      - cargo run --bin client
    silent: true
  build-client:
    cmds:
      - cargo build --bin client
    silent: true
